# -*- coding: utf-8 -*-
"""Superstore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cuhXZt6V_6PbXPhtpGtxIxd0jfPJUVlO

#Data Analysis of SuperStore Dataset

PROJECT MADE BY - SUJIT KUMAR SAHOO
"""

# IMPORTING LIBRARIES
import pandas as pd
import numpy as num
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('Superstore.csv')

df.shape

df.columns

df.head(10)

df.tail(10)

"""TOTAL FEATURES NAME ARE MENTIONED ABOVE"""

df.dtypes

"""HERE WE ARE CHECKING WHICH TYPES OF WE HAVE. ACCORDING TO ABOVE THE MAXIMUM COLUMNS WE HAVE ARE CATEGORICAL AND NUMERICAL ARE LESS."""

df.describe()

df.info()

"""#1 Count Plot

"""

df['Ship Mode'] = df['Ship Mode'].astype('category')
sns.countplot(x='Ship Mode', data=df)

df['Segment'] = df['Segment'].astype('category')
sns.countplot(x='Segment', data=df)

df['Region'] = df['Region'].astype('category')
sns.countplot(x='Region', data=df)

df['Quantity'].value_counts().plot(kind='bar')

"""#2. Pie Chart

"""

df['Ship Mode'].value_counts().plot(kind='pie')

df['Ship Mode'].value_counts().plot(kind='pie', autopct='%.3f')

"""#

#A pie chart best suits for displaying the contributions of each category in the total profit.
"""

category_df= df.groupby('Category')[['Sales','Profit']].sum()

category_df['profit %']=category_df['Profit']*100/category_df['Sales']

category_df

plt.figure(figsize=(12,6))
plt.title('Contribution of each category in Total Profit')
plt.pie(category_df.Profit, labels=category_df.index, autopct='%2.2f%%', startangle=180);

"""#3.Histogram"""

plt.hist(df['Profit'],bins=50)

df.hist(bins=50,figsize=(12,16))

"""#4.Distplot

#Quantity
"""

sns.distplot(df['Quantity'])

"""#Profit"""

sns.distplot(df['Profit'])

"""#Discount"""

sns.distplot(df['Discount'])

"""#Postal Code"""

sns.distplot(df['Postal Code'])

"""#Sales"""

sns.distplot(df['Sales'])

"""#5.Box Plot"""

sns.boxplot(df['Discount'])

sns.boxplot(df['Profit'])

sns.boxplot(df['Postal Code'])

sns.boxplot(df['Quantity'])

sns.boxplot(df['Sales'])

df['Discount'].min()

df['Discount'].max()

df['Discount'].mean()

df['Discount'].median()

df['Discount'].mode()

"""#6.Scatter Plot"""

sns.scatterplot(x='Quantity',y='Profit',data=df)

sns.scatterplot(x='Quantity',y='Profit',hue='Segment', style='Ship Mode', size='Discount',data=df)

sns.scatterplot(x='Profit', y='Sales',data=df)

"""#7.Barplot"""

sns.barplot(x='Category', y='Sales', hue=df['Segment'],data=df)

sns.barplot(x='Ship Mode', y='Sales',data=df )

"""#8.Heat Map"""

pd.crosstab(df['Category'],df['Region'])

sns.heatmap(pd.crosstab(df['Category'],df['Region']))

"""#Sales Vs Profit"""

df.groupby('Sub-Category')['Profit','Sales'].agg(['sum']).plot.bar()
plt.title('Total Profit and Sales as per Sub-Category')
plt.rcParams['figure.figsize'] = [14,10]
plt.show()

"""#Count Plot of Cities"""

print(df['State'].value_counts())
plt.figure(figsize=(18,10))
sns.countplot(x=df['State'])
plt.xticks(rotation=90)
plt.show()

"""Conclusions and Inferences:


1. The sales of the superstore are distributed among three segments: Consumer, Corporate, Home supplies. These segments are spread over four regions: West, East, Central and South. Each of the item sold belongs to one of the categories: Furniture, Office supplies or Technology.

2. Furniture is the lowest contributing category in the overall profit(only about 6%). Thus, it is the weak area to be worked on more.

3. The sub categories Book cases and tables are the ones which cause loss. Thus, they must be discarded from selling or increase the prices to make profit.

4. Supplies is the sub category of Office supplies which is in loss and thus to be taken care of. Machines in Technology are not making the considerable profit(very less). So, they have to be improved in terms of manufacturing cost to make profits more.

5. Labels, Paper and envelopes are making most of the profit from Office supplies. Furnishings, Copiers and Accesories are also major contributors of profit. All these must be maintained in a state how they are at present.

6. Central and South regions are having less sales as compared to East and West regions. There is a need of marketing or an improvement in shipment process for the East and West regions.
"""

